### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/frozen-not-in-time#1]
@charlie-quinn

Hey there, 

I can't get the ice cream cone to do what it's supposed to..

**Comment by charlie-quinn** [comment]
@sheri-thomson I'll take a peek later this evening while I'm in class. 👩‍🏫

**Comment by charlie-quinn** [comment]
Sorry about the late response @sheri-thomson 

- [ ] add a `<div>` around everything inside of `<body>` and add a class (ex: outer-banner, background, etc.)
- [ ] target this new `<div>` and add the `background-image: repeating-linear-gradient...` to it
  - this will prevent the background-image from spilling out of its container
  - [ ] also move your top/bottom borders here
- [ ] remove all spacing properties from `.html` in your main.css file (these are unnecessary since we'll be targeting everything individually)
- [ ] position your entire ice-cream cone:
  - [ ] add the `.ice-cream` to the `<div>` wrapping all of your ice-cream ingredients
  - [ ] target this `<div>` in your main.css file and add a `min-height: 480px;` to it (this will help determine most of the height that we want to use)
  - [ ] add classes `wrapper` and `grid-middle` to the `<div class="grid>` around both your text and cone (this will add a max-width, forcing everything to sit a bit closet on our screen)
  - [ ] add the class `.ingredient` to all your `<img>` tags inside of your index.html file (this will allow us to target all of these objects at the same time and apply their common positioning/sizing properties)
    - [ ] remove all positioning properties from `.cherry, .vanilla-fudge, .chocolate-chip, .mint-chip, .cone` (because we will first target them all together using `ingredient`, then finesse their individual positioning if needed)
    - _I'll give you the animation properties here since many people had a hard time getting Markbot 🤖to approve:_
    - [ ] target `.cone` and apply `animation: cone-drop-in .3s ease-in forwards;`
    - [ ] target `.mint-chip` and apply `animation: mint-drop-in .3s .3s ease-in forwards;`
    - [ ] target `.chocolate-chip` and apply `animation: choc-drop-in .3s .6s ease-in forwards;`
    - [ ] target `.vanilla-fudge` and apply `animation: vanilla-drop-in .2s .9s ease-in forwards;`
    - [ ] target `.cherry` and apply `animation: cherry-drop-in .15s 1.5s ease-in forwards;`
- [ ] setup your `@keyframes` starting with the `.cone` and following the order outlined above ☝️ 
  - [ ] .cone { 
0% {
bottom: 100%;
}
100% {
    bottom: 0;
  }
  - [ ] .mint-chip {
  0% {
    bottom: 100%;
  }
  100% {
    bottom: 104px;
  }
}
  - [ ] adjust the  100% { bottom: `??px`;} until each ingredient falls into place

- [ ] ⚠️ if your ingredients seem too large, re-download the original `.ai` file and export each `.svg` without resizing anything

**Comment by sheri-thomson** [comment]
@charlie-quinn 
So, I'm incredibly close..the drop-in animation didn't work - markbot says it wasn't an appropriate value. I have only 4% of a difference on one screen size to make it work.. is there something small i could to that won't mess up the other sizes?

**Comment by charlie-quinn** [comment]
@sheri-thomson since Markbot is incredibly picky with this assignment I'll share the exact animation values with you. Please let me know if this issue still happens after you've applied the correction animation properties:

.cone {
  animation: cone .3s ease-in forwards;
}

.mint-chip {
  animation: mint-chip .3s .3s ease-in forwards;
}

.chocolate-chip {
  left: 53%;
  animation: chocolate-chip .3s .6s ease-in forwards;
}

.vanilla-fudge {
  left: 48%;
  animation: vanilla-fudge .2s .9s ease-in forwards;
}

.cherry {
  animation: cherry .15s 1.5s ease-in forwards;
}

@keyframes cone {

  0% {
    bottom: 100%;
  }

  100% {
    bottom: 0;
  }

}

@keyframes mint-chip {

  0% {
    bottom: 100%;
  }

  100% {
    bottom: 104px;
  }

}

@keyframes chocolate-chip {

  0% {
    bottom: 100%;
  }

  100% {
    bottom: 190px;
  }

}

@keyframes vanilla-fudge {

  0% {
    bottom: 100%;
  }

  100% {
    bottom: 263px;
  }

}

@keyframes cherry {

  0% {
    bottom: 100%;
  }

  100% {
    bottom: 342px;
  }

}

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by sheri-thomson** [comment]
@charlie-quinn 
So should I be changing all the class names?

**Comment by charlie-quinn** [comment]
Oh sorry, no no – those are just the classes I had in my code. I'll revise the code above to reflect your classes.

**Comment by sheri-thomson** [comment]
I'm 1% off and the cone isn't animating.. I changed all the classes

**Comment by charlie-quinn** [comment]
Push your code and I'll take another look. 👀

**Comment by sheri-thomson** [comment]
It says it's not animated

**Comment by sheri-thomson** [comment]
It's animated but off :/

**Comment by sheri-thomson** [comment]
@charlie-quinn I GOT IT !!!!! THANK YOU, THANK YOU, THANK YOU 💃
